language: python
python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip
  - bin/pip install -r requirements.txt
  - bin/buildout -c travis.cfg

script:
  - bin/test

notifications:
  email:
    - travis-reports@ecreall.com
    - devs@imio.be
